/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace VendingMachine {
      
    export type PurchaseStruct = {productId: BigNumberish, quantity: BigNumberish, totalPaid: BigNumberish, timestamp: BigNumberish}

    export type PurchaseStructOutput = [productId: bigint, quantity: bigint, totalPaid: bigint, timestamp: bigint] & {productId: bigint, quantity: bigint, totalPaid: bigint, timestamp: bigint }
  
    }

  export interface VendingMachineInterface extends Interface {
    getFunction(nameOrSignature: "addProduct" | "admin" | "getProduct" | "getProductCount" | "getPurchases" | "nextProductId" | "products" | "purchase" | "restock" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FundsWithdrawn" | "ItemPurchased" | "ProductAdded" | "ProductRestocked"): EventFragment;

    encodeFunctionData(functionFragment: 'addProduct', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProduct', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProductCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPurchases', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextProductId', values?: undefined): string;
encodeFunctionData(functionFragment: 'products', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'purchase', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'restock', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProductCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPurchases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextProductId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'products', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'restock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace FundsWithdrawnEvent {
      export type InputTuple = [admin: AddressLike, amount: BigNumberish];
      export type OutputTuple = [admin: string, amount: bigint];
      export interface OutputObject {admin: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, productId: BigNumberish, quantity: BigNumberish, totalPaid: BigNumberish];
      export type OutputTuple = [buyer: string, productId: bigint, quantity: bigint, totalPaid: bigint];
      export interface OutputObject {buyer: string, productId: bigint, quantity: bigint, totalPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductAddedEvent {
      export type InputTuple = [productId: BigNumberish, name: string, price: BigNumberish, stock: BigNumberish];
      export type OutputTuple = [productId: bigint, name: string, price: bigint, stock: bigint];
      export interface OutputObject {productId: bigint, name: string, price: bigint, stock: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductRestockedEvent {
      export type InputTuple = [productId: BigNumberish, addedQuantity: BigNumberish, newStock: BigNumberish];
      export type OutputTuple = [productId: bigint, addedQuantity: bigint, newStock: bigint];
      export interface OutputObject {productId: bigint, addedQuantity: bigint, newStock: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VendingMachine extends BaseContract {
    
    connect(runner?: ContractRunner | null): VendingMachine;
    waitForDeployment(): Promise<this>;

    interface: VendingMachineInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addProduct: TypedContractMethod<
      [_name: string, _price: BigNumberish, _stock: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getProduct: TypedContractMethod<
      [_productId: BigNumberish, ],
      [[string, bigint, bigint] & {name: string, price: bigint, stock: bigint }],
      'view'
    >
    

    
    getProductCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPurchases: TypedContractMethod<
      [_buyer: AddressLike, ],
      [VendingMachine.PurchaseStructOutput[]],
      'view'
    >
    

    
    nextProductId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    products: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean] & {name: string, price: bigint, stock: bigint, exists: boolean }],
      'view'
    >
    

    
    purchase: TypedContractMethod<
      [_productId: BigNumberish, _quantity: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    restock: TypedContractMethod<
      [_productId: BigNumberish, _quantity: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addProduct'): TypedContractMethod<
      [_name: string, _price: BigNumberish, _stock: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getProduct'): TypedContractMethod<
      [_productId: BigNumberish, ],
      [[string, bigint, bigint] & {name: string, price: bigint, stock: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getProductCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPurchases'): TypedContractMethod<
      [_buyer: AddressLike, ],
      [VendingMachine.PurchaseStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'nextProductId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'products'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean] & {name: string, price: bigint, stock: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'purchase'): TypedContractMethod<
      [_productId: BigNumberish, _quantity: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'restock'): TypedContractMethod<
      [_productId: BigNumberish, _quantity: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FundsWithdrawn'): TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
getEvent(key: 'ItemPurchased'): TypedContractEvent<ItemPurchasedEvent.InputTuple, ItemPurchasedEvent.OutputTuple, ItemPurchasedEvent.OutputObject>;
getEvent(key: 'ProductAdded'): TypedContractEvent<ProductAddedEvent.InputTuple, ProductAddedEvent.OutputTuple, ProductAddedEvent.OutputObject>;
getEvent(key: 'ProductRestocked'): TypedContractEvent<ProductRestockedEvent.InputTuple, ProductRestockedEvent.OutputTuple, ProductRestockedEvent.OutputObject>;

    filters: {
      
      'FundsWithdrawn(address,uint256)': TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
      FundsWithdrawn: TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
    

      'ItemPurchased(address,uint256,uint256,uint256)': TypedContractEvent<ItemPurchasedEvent.InputTuple, ItemPurchasedEvent.OutputTuple, ItemPurchasedEvent.OutputObject>;
      ItemPurchased: TypedContractEvent<ItemPurchasedEvent.InputTuple, ItemPurchasedEvent.OutputTuple, ItemPurchasedEvent.OutputObject>;
    

      'ProductAdded(uint256,string,uint256,uint256)': TypedContractEvent<ProductAddedEvent.InputTuple, ProductAddedEvent.OutputTuple, ProductAddedEvent.OutputObject>;
      ProductAdded: TypedContractEvent<ProductAddedEvent.InputTuple, ProductAddedEvent.OutputTuple, ProductAddedEvent.OutputObject>;
    

      'ProductRestocked(uint256,uint256,uint256)': TypedContractEvent<ProductRestockedEvent.InputTuple, ProductRestockedEvent.OutputTuple, ProductRestockedEvent.OutputObject>;
      ProductRestocked: TypedContractEvent<ProductRestockedEvent.InputTuple, ProductRestockedEvent.OutputTuple, ProductRestockedEvent.OutputObject>;
    
    };
  }