/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EventTicketsInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "buyResale" | "buyTicket" | "cancelSale" | "createEvent" | "events" | "getEventCount" | "getEventInfo" | "getTicket" | "getTicketCount" | "listForSale" | "nextEventId" | "nextTicketId" | "tickets" | "transferTicket" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EventCreated" | "TicketListedForSale" | "TicketPurchased" | "TicketSaleCancelled" | "TicketSaleCompleted" | "TicketTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyResale', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyTicket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelSale', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createEvent', values: [string, string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'events', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEventCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getEventInfo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTicket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTicketCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'listForSale', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextEventId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextTicketId', values?: undefined): string;
encodeFunctionData(functionFragment: 'tickets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferTicket', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyResale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyTicket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelSale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'events', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEventCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEventInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTicket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTicketCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listForSale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextEventId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextTicketId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tickets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferTicket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace EventCreatedEvent {
      export type InputTuple = [eventId: BigNumberish, name: string, ticketPrice: BigNumberish, totalTickets: BigNumberish];
      export type OutputTuple = [eventId: bigint, name: string, ticketPrice: bigint, totalTickets: bigint];
      export interface OutputObject {eventId: bigint, name: string, ticketPrice: bigint, totalTickets: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketListedForSaleEvent {
      export type InputTuple = [ticketId: BigNumberish, price: BigNumberish];
      export type OutputTuple = [ticketId: bigint, price: bigint];
      export interface OutputObject {ticketId: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketPurchasedEvent {
      export type InputTuple = [ticketId: BigNumberish, eventId: BigNumberish, buyer: AddressLike, price: BigNumberish];
      export type OutputTuple = [ticketId: bigint, eventId: bigint, buyer: string, price: bigint];
      export interface OutputObject {ticketId: bigint, eventId: bigint, buyer: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketSaleCancelledEvent {
      export type InputTuple = [ticketId: BigNumberish];
      export type OutputTuple = [ticketId: bigint];
      export interface OutputObject {ticketId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketSaleCompletedEvent {
      export type InputTuple = [ticketId: BigNumberish, seller: AddressLike, buyer: AddressLike, price: BigNumberish];
      export type OutputTuple = [ticketId: bigint, seller: string, buyer: string, price: bigint];
      export interface OutputObject {ticketId: bigint, seller: string, buyer: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketTransferredEvent {
      export type InputTuple = [ticketId: BigNumberish, from: AddressLike, to: AddressLike];
      export type OutputTuple = [ticketId: bigint, from: string, to: string];
      export interface OutputObject {ticketId: bigint, from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EventTickets extends BaseContract {
    
    connect(runner?: ContractRunner | null): EventTickets;
    waitForDeployment(): Promise<this>;

    interface: EventTicketsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    buyResale: TypedContractMethod<
      [_ticketId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    buyTicket: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    cancelSale: TypedContractMethod<
      [_ticketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createEvent: TypedContractMethod<
      [_name: string, _date: string, _venue: string, _ticketPrice: BigNumberish, _totalTickets: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    events: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, boolean] & {name: string, date: string, venue: string, ticketPrice: bigint, totalTickets: bigint, ticketsSold: bigint, exists: boolean }],
      'view'
    >
    

    
    getEventCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getEventInfo: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint] & {name: string, date: string, venue: string, ticketPrice: bigint, totalTickets: bigint, ticketsSold: bigint }],
      'view'
    >
    

    
    getTicket: TypedContractMethod<
      [_ticketId: BigNumberish, ],
      [[bigint, string, boolean, bigint] & {eventId: bigint, owner: string, forSale: boolean, resalePrice: bigint }],
      'view'
    >
    

    
    getTicketCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    listForSale: TypedContractMethod<
      [_ticketId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    nextEventId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextTicketId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tickets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, boolean, bigint, boolean] & {eventId: bigint, owner: string, forSale: boolean, resalePrice: bigint, exists: boolean }],
      'view'
    >
    

    
    transferTicket: TypedContractMethod<
      [_ticketId: BigNumberish, _to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buyResale'): TypedContractMethod<
      [_ticketId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'buyTicket'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelSale'): TypedContractMethod<
      [_ticketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createEvent'): TypedContractMethod<
      [_name: string, _date: string, _venue: string, _ticketPrice: BigNumberish, _totalTickets: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'events'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, boolean] & {name: string, date: string, venue: string, ticketPrice: bigint, totalTickets: bigint, ticketsSold: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getEventCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getEventInfo'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint] & {name: string, date: string, venue: string, ticketPrice: bigint, totalTickets: bigint, ticketsSold: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTicket'): TypedContractMethod<
      [_ticketId: BigNumberish, ],
      [[bigint, string, boolean, bigint] & {eventId: bigint, owner: string, forSale: boolean, resalePrice: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTicketCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'listForSale'): TypedContractMethod<
      [_ticketId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextEventId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextTicketId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tickets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, boolean, bigint, boolean] & {eventId: bigint, owner: string, forSale: boolean, resalePrice: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'transferTicket'): TypedContractMethod<
      [_ticketId: BigNumberish, _to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EventCreated'): TypedContractEvent<EventCreatedEvent.InputTuple, EventCreatedEvent.OutputTuple, EventCreatedEvent.OutputObject>;
getEvent(key: 'TicketListedForSale'): TypedContractEvent<TicketListedForSaleEvent.InputTuple, TicketListedForSaleEvent.OutputTuple, TicketListedForSaleEvent.OutputObject>;
getEvent(key: 'TicketPurchased'): TypedContractEvent<TicketPurchasedEvent.InputTuple, TicketPurchasedEvent.OutputTuple, TicketPurchasedEvent.OutputObject>;
getEvent(key: 'TicketSaleCancelled'): TypedContractEvent<TicketSaleCancelledEvent.InputTuple, TicketSaleCancelledEvent.OutputTuple, TicketSaleCancelledEvent.OutputObject>;
getEvent(key: 'TicketSaleCompleted'): TypedContractEvent<TicketSaleCompletedEvent.InputTuple, TicketSaleCompletedEvent.OutputTuple, TicketSaleCompletedEvent.OutputObject>;
getEvent(key: 'TicketTransferred'): TypedContractEvent<TicketTransferredEvent.InputTuple, TicketTransferredEvent.OutputTuple, TicketTransferredEvent.OutputObject>;

    filters: {
      
      'EventCreated(uint256,string,uint256,uint256)': TypedContractEvent<EventCreatedEvent.InputTuple, EventCreatedEvent.OutputTuple, EventCreatedEvent.OutputObject>;
      EventCreated: TypedContractEvent<EventCreatedEvent.InputTuple, EventCreatedEvent.OutputTuple, EventCreatedEvent.OutputObject>;
    

      'TicketListedForSale(uint256,uint256)': TypedContractEvent<TicketListedForSaleEvent.InputTuple, TicketListedForSaleEvent.OutputTuple, TicketListedForSaleEvent.OutputObject>;
      TicketListedForSale: TypedContractEvent<TicketListedForSaleEvent.InputTuple, TicketListedForSaleEvent.OutputTuple, TicketListedForSaleEvent.OutputObject>;
    

      'TicketPurchased(uint256,uint256,address,uint256)': TypedContractEvent<TicketPurchasedEvent.InputTuple, TicketPurchasedEvent.OutputTuple, TicketPurchasedEvent.OutputObject>;
      TicketPurchased: TypedContractEvent<TicketPurchasedEvent.InputTuple, TicketPurchasedEvent.OutputTuple, TicketPurchasedEvent.OutputObject>;
    

      'TicketSaleCancelled(uint256)': TypedContractEvent<TicketSaleCancelledEvent.InputTuple, TicketSaleCancelledEvent.OutputTuple, TicketSaleCancelledEvent.OutputObject>;
      TicketSaleCancelled: TypedContractEvent<TicketSaleCancelledEvent.InputTuple, TicketSaleCancelledEvent.OutputTuple, TicketSaleCancelledEvent.OutputObject>;
    

      'TicketSaleCompleted(uint256,address,address,uint256)': TypedContractEvent<TicketSaleCompletedEvent.InputTuple, TicketSaleCompletedEvent.OutputTuple, TicketSaleCompletedEvent.OutputObject>;
      TicketSaleCompleted: TypedContractEvent<TicketSaleCompletedEvent.InputTuple, TicketSaleCompletedEvent.OutputTuple, TicketSaleCompletedEvent.OutputObject>;
    

      'TicketTransferred(uint256,address,address)': TypedContractEvent<TicketTransferredEvent.InputTuple, TicketTransferredEvent.OutputTuple, TicketTransferredEvent.OutputObject>;
      TicketTransferred: TypedContractEvent<TicketTransferredEvent.InputTuple, TicketTransferredEvent.OutputTuple, TicketTransferredEvent.OutputObject>;
    
    };
  }